name: Export competitions (15m)

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    # Non-secret config (safe to keep in repo)
    env:
      DISCOVERY_ORDER: "brave,serper,google"
      DISCOVERY_DAILY_MAX: "20"
      CSE_PAGES_PER_QUERY: "2"
      CSE_DATE_RESTRICT: "m12"
      BRAVE_REGION: "hk"
      SERPER_GL: "hk"
      SERPER_HL: "en"
      EXTRACTOR_ORDER: "rules,deepseek"  # no ollama in Actions
      HTML_ACCEPT_SCORE: "70"
      MIN_SCORE_TO_USE_CLOUD: "50"
      ALLOWED_ORIGINS: "http://localhost:3000"

    steps:
      # Checkout THIS repo (frontend)
      - uses: actions/checkout@v4

      # Checkout backend repo where export_json.py lives
      - name: Checkout hkcompete-backend
        uses: actions/checkout@v4
        with:
          # If under your account, keep this:
          repository: Suhansh21/hkcompete-backend
          # If it's under an org instead, use:
          # repository: hkcompete/hkcompete-backend
          path: hkcompete-backend
          # If the repo is private, add a PAT (repo scope) as GH_TOKEN secret and uncomment:
          # token: ${{ secrets.GH_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (backend requirements)
        run: |
          python -m pip install -U pip
          if [ -f hkcompete-backend/requirements.txt ]; then
            pip install -r hkcompete-backend/requirements.txt
          fi

      - name: Quick path check
        run: |
          echo "== repo root ==" && pwd && ls -la
          echo "== hkcompete-backend ==" && ls -la hkcompete-backend || true
          echo "== look for export_json.py ==" && find hkcompete-backend -maxdepth 2 -iname "export_json.py" -print || true

      - name: Create .env for exporter
        run: |
          cat > .env << 'EOF'
          # === Database & Backend ===
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

          # === Discovery/Search Settings ===
          DISCOVERY_ORDER=${DISCOVERY_ORDER}
          DISCOVERY_DAILY_MAX=${DISCOVERY_DAILY_MAX}
          CSE_PAGES_PER_QUERY=${CSE_PAGES_PER_QUERY}
          CSE_DATE_RESTRICT=${CSE_DATE_RESTRICT}

          # --- Brave ---
          BRAVE_API_KEY=${{ secrets.BRAVE_API_KEY }}
          BRAVE_REGION=${BRAVE_REGION}

          # --- Serper.dev ---
          SERPER_API_KEY=${{ secrets.SERPER_API_KEY }}
          SERPER_GL=${SERPER_GL}
          SERPER_HL=${SERPER_HL}

          # --- SerpAPI (optional) ---
          SERPAPI_KEY=${{ secrets.SERPAPI_KEY }}

          # --- Google CSE ---
          GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CSE_ID=${{ secrets.GOOGLE_CSE_ID }}

          # === Extractors ===
          EXTRACTOR_ORDER=${EXTRACTOR_ORDER}
          HTML_ACCEPT_SCORE=${HTML_ACCEPT_SCORE}
          MIN_SCORE_TO_USE_CLOUD=${MIN_SCORE_TO_USE_CLOUD}

          # --- Ollama (disabled on Actions) ---
          OLLAMA_HOST=
          OLLAMA_MODEL=

          # --- DeepSeek (optional) ---
          DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}
          DEEPSEEK_MODEL=deepseek-chat

          # --- Optional / Unused ---
          OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}
          MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}
          MISTRAL_MODEL=mistral-large-latest
          MISTRAL_DAILY_MAX=10
          EOF


      - name: Run exporter
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          set -e
          if [ -f hkcompete-backend/export_json.py ]; then
            python hkcompete-backend/export_json.py --out hkcompete-backend/competitions.json
          elif [ -f hkcompete-backend/scripts/export_json.py ]; then
            python hkcompete-backend/scripts/export_json.py --out hkcompete-backend/competitions.json
          else
            echo "export_json.py not found under hkcompete-backend/"
            exit 1
          fi

      - name: Post-export diagnostics
        run: |
          set -e
          echo "== ls -la hkcompete-backend =="
          ls -la hkcompete-backend || true
          echo "== find JSONs under hkcompete-backend =="
          find hkcompete-backend -maxdepth 2 -type f -name "*.json" -print || true
          if [ ! -f hkcompete-backend/competitions.json ]; then
            echo "ERROR: hkcompete-backend/competitions.json not found. See listing above."
            exit 2
          fi
          echo "== head of competitions.json =="
          head -c 500 hkcompete-backend/competitions.json || true

      - name: Copy output to repo root
        run: |
          cp hkcompete-backend/competitions.json competitions.json
          ls -la . | sed -n '1,100p'

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: competitions-json
          path: |
            competitions.json
            hkcompete-backend/competitions.json
          if-no-files-found: warn

      - name: Commit competitions.json (always)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add competitions.json || true
          git commit -m "update: competitions.json (auto commit) [skip ci]" || echo "No changes to commit"
          git push || echo "Push skipped (no new commit)"


 
