name: Export Competitions

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch: {}

jobs:
  export:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install beautifulsoup4 dateparser requests

      - name: Run scraper (write public/competitions.json)
        run: |
          python scraper.py --out public/competitions.json --pretty --limit 200
        working-directory: .

      - name: Commit export
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/competitions.json
          git commit -m "export: refresh competitions" || echo "No changes"
          git push
