name: Final Secrets Verification
on:
  workflow_dispatch:
jobs:
  verify-secrets:
    runs-on: ubuntu-latest
    steps:
    steps:
      # Checkout the frontend repo (this repo)
      - uses: actions/checkout@v4

      # Checkout the backend repo where export_json.py lives
      - name: Checkout hkcompete-backend
        uses: actions/checkout@v4
        with:
          repository: hkcompete/hkcompete-backend
          path: backend
          # If it's private, uncomment and add token in secrets:
          # token: ${{ secrets.GH_TOKEN }}

      # Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies (backend)
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi

      # Create .env for exporter
      - name: Create .env for exporter
        run: |
          cat > .env << 'EOF'
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          # ... copy the rest of your ENV content from before ...
          EOF

      # Run exporter from backend folder
      - name: Run exporter
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          if [ -f backend/export_json.py ]; then
            python backend/export_json.py --out competitions.json
          elif [ -f backend/scripts/export_json.py ]; then
            python backend/scripts/export_json.py --out competitions.json
          else
            echo "export_json.py not found in backend/"
            exit 1
          fi

      # Commit if changed
      - name: Commit if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add competitions.json || true
          if git diff --staged --quiet; then
            echo "No changes."
          else
            git commit -m "refresh: competitions.json [skip ci]"
            git push
          fi


