name: Export Competitions

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch: {}

# This is fine to keep even if we push via PAT
permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo (no credentials so we can push with PAT later)
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install beautifulsoup4 dateparser requests

      - name: Run scraper (write public/competitions.json)
        run: |
          python scraper.py --out public/competitions.json --pretty
        working-directory: .

      - name: Commit export
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/competitions.json
          git commit -m "export: refresh competitions" || echo "No changes"

      - name: Push changes (PAT)
        env:
          PAT: ${{ secrets.PUSH_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
        run: |
          git push "https://x-access-token:${PAT}@github.com/${REPO}.git" HEAD:${BRANCH}

  
