name: Export Competitions

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

# 👇 give the workflow write access to the repo
permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install beautifulsoup4 dateparser requests

      - name: Run scraper (write public/competitions.json)
        run: |
          python scraper.py --out public/competitions.json --pretty
        working-directory: .

      - name: Commit export
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/competitions.json
          git commit -m "export: refresh competitions" || echo "No changes"

      # 👇 push using the GITHUB_TOKEN to THIS repo explicitly
      - name: Push changes
        run: |
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref_name }}
