name: export-json

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "Where to save the JSON file"
        required: true
        default: "export/export.json"
        type: string
      json:
        description: "JSON payload to write (leave as {} to only include run metadata)"
        required: false
        default: "{}"
        type: string
      commit_to_repo:
        description: "Also commit the file back to the repo?"
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    env:
      OUTFILE: ${{ github.event.inputs.filename }}
      PAYLOAD: ${{ github.event.inputs.json }}
      GITHUB_RUN_ID: ${{ github.run_id }}
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_REF_NAME: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Validate & write JSON
        run: |
          python - <<'PY'
          import json, os, pathlib, sys
          payload = os.getenv("PAYLOAD") or "{}"
          try:
              data = json.loads(payload)
          except Exception as e:
              print(f"❌ Invalid JSON: {e}")
              sys.exit(1)

          # Add run metadata without overwriting if user already provided keys
          data.setdefault("run_id", os.getenv("GITHUB_RUN_ID"))
          data.setdefault("commit_sha", os.getenv("GITHUB_SHA"))
          data.setdefault("ref", os.getenv("GITHUB_REF_NAME"))

          p = pathlib.Path(os.getenv("OUTFILE"))
          p.parent.mkdir(parents=True, exist_ok=True)
          p.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
          print(f"✅ Wrote {p}")
          PY

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: exported-json
          path: ${{ github.event.inputs.filename }}

      - name: Commit & push (optional)
        if: ${{ fromJSON(github.event.inputs.commit_to_repo || 'false') }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "${{ github.event.inputs.filename }}"
          if git diff --cached --quiet; then
            echo "No changes to commit"; exit 0
          fi
          git commit -m "chore: export JSON via workflow"
          git push


