name: Nightly Scrape

on:
  schedule:
    - cron: '0 18 * * *'   # 02:00 Asia/Singapore (GitHub uses UTC)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: nightly-scrape
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show repo tree (debug)
        shell: bash
        run: |
          pwd
          ls -la
          find . -maxdepth 2 -type f \( -name "requirements.txt" -o -name "scraper.py" \) | sort || true

      - name: Show repo tree (debug)
        shell: bash
        run: |
          pwd
          ls -la
          find . -maxdepth 2 -type f \( -name "requirements.txt" -o -name "scraper.py" \) | sort || true

      # Create a minimal requirements.txt if it's missing
      - name: Ensure requirements.txt exists
        shell: bash
        run: |
          if [ ! -f requirements.txt ]; then
            echo "requests" > requirements.txt
            echo "beautifulsoup4" >> requirements.txt
            echo "python-dotenv" >> requirements.txt
            echo "certifi" >> requirements.txt
          fi

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure public/competitions.json exists
        shell: bash
        run: |
          mkdir -p public
          [ -f public/competitions.json ] || echo "[]" > public/competitions.json

      - name: Run scraper (static export, rules-only)
        env:
          EXTRACTOR_ORDER: rules
          CSE_PAGES_PER_QUERY: '2'
          CSE_DATE_RESTRICT: m12
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
        run: |
          python scraper.py --out public/competitions.json --pretty

      - name: Commit updated JSON if changed
        shell: bash
        run: |
          if git diff --quiet -- public/competitions.json; then
            echo "No changes"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add public/competitions.json
            git commit -m "nightly scrape"
            git push
          fi
