name: secrets-final-verify

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      FIREBASE_API_KEY:              ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN:          ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_SUPABASE_URL:      ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
    steps:
      - name: Check required secrets exist (values never printed)
        run: |
          python - <<'PY'
          import os, sys, hashlib, json
          required = [
            "FIREBASE_API_KEY",
            "FIREBASE_AUTH_DOMAIN",
            "NEXT_PUBLIC_SUPABASE_URL",
            "NEXT_PUBLIC_SUPABASE_ANON_KEY",
          ]
          missing = [k for k in required if not os.getenv(k)]
          if missing:
              print("❌ Missing secrets:", ", ".join(missing))
              sys.exit(1)
          report = {}
          for k in required:
              v = os.getenv(k, "")
              report[k] = {
                "present": True,
                "len": len(v),
                "sha256_8": hashlib.sha256(v.encode()).hexdigest()[:8],
              }
          print(json.dumps(report, indent=2))
          print("✅ All required secrets are present")
          PY
