name: Nightly Scrape

on:
  schedule:
    # 02:00 Asia/Singapore daily (GitHub uses UTC)
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: nightly-scrape
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Show repo tree (debug)
        run: |
          pwd
          ls -la
          git ls-files | sed -n '1,200p'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper (static export, rules-only)
        env:
          EXTRACTOR_ORDER: rules
          CSE_PAGES_PER_QUERY: 2
          CSE_DATE_RESTRICT: m12
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
        run: |
          python scraper.py --out public/competitions.json --pretty

      - name: Commit updated JSON if changed
        run: |
          if git diff --quiet -- public/competitions.json; then
            echo "No changes"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add public/competitions.json
            git commit -m "nightly scrape"
            git push
          fi

