name: Secrets final verify
on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Validate required secrets
        env:
          SUPABASE_URL:    ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY:    ${{ secrets.SUPABASE_KEY }}
          DATABASE_URL:    ${{ secrets.DATABASE_URL }}
          SERPER_API_KEY:  ${{ secrets.SERPER_API_KEY }}
          GOOGLE_API_KEY:  ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CSE_ID:   ${{ secrets.GOOGLE_CSE_ID }}
        run: |
          set -e
          : "${SUPABASE_URL:?SUPABASE_URL missing}"
          : "${SUPABASE_KEY:?SUPABASE_KEY missing}"
          : "${DATABASE_URL:?DATABASE_URL missing}"
          : "${SERPER_API_KEY:?SERPER_API_KEY missing}"
          : "${GOOGLE_API_KEY:?GOOGLE_API_KEY missing}"
          : "${GOOGLE_CSE_ID:?GOOGLE_CSE_ID missing}"
          echo "All required secrets are present."

      - name: Create .env with masked values
        env:
          SUPABASE_URL:    ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY:    ${{ secrets.SUPABASE_KEY }}
          DATABASE_URL:    ${{ secrets.DATABASE_URL }}
          SERPER_API_KEY:  ${{ secrets.SERPER_API_KEY }}
          GOOGLE_API_KEY:  ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CSE_ID:   ${{ secrets.GOOGLE_CSE_ID }}
        run: |
          cat > .env << 'EOF'
          SUPABASE_URL=${SUPABASE_URL}
          SUPABASE_KEY=${SUPABASE_KEY}
          DATABASE_URL=${DATABASE_URL}
          SERPER_API_KEY=${SERPER_API_KEY}
          GOOGLE_API_KEY=${GOOGLE_API_KEY}
          GOOGLE_CSE_ID=${GOOGLE_CSE_ID}
          EOF
          echo "Wrote .env (values will be masked in logs)."
          printf "Preview: "; head -n 2 .env

      - name: Upload .env artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-check
          path: .env
