name: export-core-secrets-json

on:
  workflow_dispatch:
    inputs:
      commit_to_repo:
        description: "Also commit export/core-secrets.json back to the repo? (NOT recommended)"
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    env:
      # From your screenshot — these will be empty if not defined, and we’ll skip empties.
      DATABASE_URL:        ${{ secrets.DATABASE_URL }}
      DEEPSEEK_API_KEY:    ${{ secrets.DEEPSEEK_API_KEY }}
      GOOGLE_API_KEY:      ${{ secrets.GOOGLE_API_KEY }}
      GOOGLE_CSE_ID:       ${{ secrets.GOOGLE_CSE_ID }}
      MISTRAL_API_KEY:     ${{ secrets.MISTRAL_API_KEY }}
      OPENROUTER_API_KEY:  ${{ secrets.OPENROUTER_API_KEY }}
      SERPAPI_KEY:         ${{ secrets.SERPAPI_KEY }}
      SERPER_API_KEY:      ${{ secrets.SERPER_API_KEY }}
      SUPABASE_URL:        ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY:        ${{ secrets.SUPABASE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate export/core-secrets.json (skip empties)
        run: |
          python - <<'PY'
          import os, json, pathlib, sys
          names = [
            "DATABASE_URL","DEEPSEEK_API_KEY","GOOGLE_API_KEY","GOOGLE_CSE_ID",
            "MISTRAL_API_KEY","OPENROUTER_API_KEY","SERPAPI_KEY","SERPER_API_KEY",
            "SUPABASE_URL","SUPABASE_KEY",
          ]
          out = {k: os.environ.get(k) for k in names if os.environ.get(k)}
          if not out:
            print("❌ No matching secrets were found on this repo.")
            sys.exit(1)
          p = pathlib.Path("export") / "core-secrets.json"
          p.parent.mkdir(parents=True, exist_ok=True)
          p.write_text(json.dumps(out, indent=2), encoding="utf-8")
          print(f"✅ Wrote {p} with {len(out)} keys")
          PY

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: core-secrets
          path: export/core-secrets.json

      - name: Commit & push (optional — be careful, this writes secrets to git)
        if: ${{ fromJSON(github.event.inputs.commit_to_repo || 'false') }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add export/core-secrets.json
          if git diff --cached --quiet; then
            echo "No changes to commit"; exit 0
          fi
          git commit -m "chore: export core secrets (DANGEROUS — contains secrets)"
          git push

