name: Export Competitions (manual + cron)

on:
  workflow_dispatch:      # show "Run workflow" button
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes UTC

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create .env (optional)
        run: |
          cat > .env << 'EOF'
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
          EOF

      - name: Ensure exporter exists (create stub if missing)
        run: |
          mkdir -p scripts
          if [ ! -f scripts/export_json.py ]; then
            echo "No scripts/export_json.py found — creating a stub so the pipeline runs."
            cat > scripts/export_json.py << 'PY'
import json, time, argparse
p = argparse.ArgumentParser()
p.add_argument("--out", default="competitions.json")
args = p.parse_args()
data = {
  "generated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
  "source": "stub-exporter",
  "items": []
}
with open(args.out, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print(f"Wrote {args.out}")
PY
          fi
          python -V
          ls -la scripts

      - name: Run exporter
        run: |
          python scripts/export_json.py --out competitions.json
          echo "== repo root after export ==" && ls -la
          echo "== preview competitions.json ==" && head -n 30 competitions.json || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: competitions-json
          path: competitions.json
          if-no-files-found: error

      - name: Commit competitions.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f competitions.json
          git commit -m "update: competitions.json [skip ci]" || echo "No changes to commit"
          git push || echo "Push skipped"





