name: EZ Manual Test

on:
  workflow_dispatch:  # this is what shows the Run button
jobs:
  export:
    runs-on: ubuntu-latest

    env:
      DISCOVERY_ORDER: "brave,serper,google"
      DISCOVERY_DAILY_MAX: "20"
      CSE_PAGES_PER_QUERY: "2"
      CSE_DATE_RESTRICT: "m12"
      BRAVE_REGION: "hk"
      SERPER_GL: "hk"
      SERPER_HL: "en"
      EXTRACTOR_ORDER: "rules,deepseek"
      HTML_ACCEPT_SCORE: "70"
      MIN_SCORE_TO_USE_CLOUD: "50"
      ALLOWED_ORIGINS: "http://localhost:3000"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create .env for exporter
        run: |
          cat > .env << 'EOF'
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
          DISCOVERY_ORDER=${DISCOVERY_ORDER}
          DISCOVERY_DAILY_MAX=${DISCOVERY_DAILY_MAX}
          CSE_PAGES_PER_QUERY=${CSE_PAGES_PER_QUERY}
          CSE_DATE_RESTRICT=${CSE_DATE_RESTRICT}
          BRAVE_API_KEY=${{ secrets.BRAVE_API_KEY }}
          BRAVE_REGION=${BRAVE_REGION}
          SERPER_API_KEY=${{ secrets.SERPER_API_KEY }}
          SERPER_GL=${SERPER_GL}
          SERPER_HL=${SERPER_HL}
          SERPAPI_KEY=${{ secrets.SERPAPI_KEY }}
          GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CSE_ID=${{ secrets.GOOGLE_CSE_ID }}
          EXTRACTOR_ORDER=${EXTRACTOR_ORDER}
          HTML_ACCEPT_SCORE=${HTML_ACCEPT_SCORE}
          MIN_SCORE_TO_USE_CLOUD=${MIN_SCORE_TO_USE_CLOUD}
          DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}
          DEEPSEEK_MODEL=deepseek-chat
          OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}
          MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}
          MISTRAL_MODEL=mistral-large-latest
          MISTRAL_DAILY_MAX=10
          EOF

      - name: Run exporter
        run: python export_json.py --out competitions.json

      - name: Commit if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add competitions.json
          if git diff --staged --quiet; then
            echo "No changes."
          else
            git commit -m "refresh: competitions.json [skip ci]"
            git push
          fi






