name: secrets-inventory
on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  list:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}   # let gh call GitHub API
    steps:
      - name: Repo info
        run: |
          echo "Repo: $GITHUB_REPOSITORY"

      - name: Repository VARIABLES (names only)
        run: |
          gh api -H "Accept: application/vnd.github+json" \
            "/repos/$GITHUB_REPOSITORY/actions/variables" \
            | jq -r '.variables[]?.name' || true

      - name: Repository SECRETS (names only)
        run: |
          gh api -H "Accept: application/vnd.github+json" \
            "/repos/$GITHUB_REPOSITORY/actions/secrets" \
            | jq -r '.secrets[]?.name' || true

      - name: Environments (names)
        run: |
          gh api -H "Accept: application/vnd.github+json" \
            "/repos/$GITHUB_REPOSITORY/environments" \
            | jq -r '.environments[]?.name' || true

      - name: Environment SECRETS (names only, per env)
        run: |
          envs=$(gh api -H "Accept: application/vnd.github+json" "/repos/$GITHUB_REPOSITORY/environments" | jq -r '.environments[]?.name')
          for e in $envs; do
            echo "== $e =="
            gh api -H "Accept: application/vnd.github+json" \
              "/repos/$GITHUB_REPOSITORY/environments/$e/secrets" \
              | jq -r '.secrets[]?.name' || true
            echo
          done


