name: secrets-final-verifyz
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    steps:
      - name: Check required values exist (no leaks)
        shell: bash
        run: |
          set -euo pipefail
          missing=()
          [ -n "${SUPABASE_URL:-}" ] || missing+=("SUPABASE_URL")
          [ -n "${SUPABASE_KEY:-}" ] || missing+=("SUPABASE_KEY")

          if [ ${#missing[@]} -gt 0 ]; then
            echo "❌ Missing: ${missing[*]}"
            exit 1
          fi

          # Redacted fingerprints
          url_hash=$(printf "%s" "$SUPABASE_URL" | sha256sum | cut -c1-8)
          key_hash=$(printf "%s" "$SUPABASE_KEY" | sha256sum | cut -c1-8)
          echo "SUPABASE_URL len=${#SUPABASE_URL} sha256_8=$url_hash"
          echo "SUPABASE_KEY len=${#SUPABASE_KEY} sha256_8=$key_hash"
          echo "✅ Both Supabase secrets are present"


